name: sudema_app
description: "Uma solução mobile para a SUDEMA/PB"
publish_to: 'none' # Remove this line if você quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Funcionalidades principais
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.2

  # Google Maps e localização
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  google_maps_webservice: ^0.0.18
  flutter_google_places: ^0.3.0

  # Utilidades
  http: ^0.13.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/logo_gov.webp
    - assets/images/logo_sudema.webp
    - assets/images/megafone.png
    - assets/images/denuncia_bg.png
    - assets/images/bauneabilidade.jpg
    - assets/images/fiscalizacao.jpg
    - assets/images/licenciamento.jpg
    - assets/images/educacao_ambiental.jpg
    - assets/images/denuncia.jpg


dependency_overrides:
  google_api_headers:
    git:
      url: https://github.com/zeshuaro/google_api_headers.git
      ref: main

