name: sudema_app
description: "Uma solução mobile para a SUDEMA/PB"
publish_to: 'none' # Remove this line if você quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Funcionalidades principais
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.2

  # Google Maps e localização
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  google_maps_webservice: ^0.0.18
  flutter_google_places: ^0.3.0
  google_place: ^0.4.7
  google_fonts: ^4.0.4

  # Utilidades
  http: ^0.13.6
  cupertino_icons: ^1.0.8


  #Desconhecidas
  flutter_svg: ^2.0.7
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/



dependency_overrides:
  google_api_headers:
    git:
      url: https://github.com/zeshuaro/google_api_headers.git
      ref: main

